name: Rafika
remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: thelehhman
    github: thelehhman
    linkedIn: in/thelehhman # format: locale/username
